namespace PeanutVision.MultiCamDriver.Camera;

/// <summary>
/// Parses .cam files (INI-style format generated by MultiCam Studio)
/// to extract camera metadata.
/// </summary>
public static class CamFileParser
{
    /// <summary>
    /// Parses a .cam file and returns its metadata.
    /// Later sections (User Settings) override earlier values.
    /// </summary>
    public static CamFileInfo Parse(string filePath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(filePath);

        if (!File.Exists(filePath))
            throw new FileNotFoundException($"Cam file not found: '{filePath}'", filePath);

        var lines = File.ReadAllLines(filePath);
        return ParseLines(lines, filePath);
    }

    public static CamFileInfo ParseLines(string[] lines, string filePath)
    {
        var fileName = Path.GetFileName(filePath);
        var parameters = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        string manufacturer = "Unknown";
        string cameraModel = "Unknown";

        foreach (var rawLine in lines)
        {
            var line = rawLine.Trim();

            // Extract header comment metadata
            if (line.StartsWith(';'))
            {
                var commentContent = line.TrimStart(';').Trim();

                if (commentContent.StartsWith("Camera Manufacturer:", StringComparison.OrdinalIgnoreCase))
                {
                    manufacturer = commentContent["Camera Manufacturer:".Length..].Trim();
                }
                else if (commentContent.StartsWith("Camera Model:", StringComparison.OrdinalIgnoreCase))
                {
                    cameraModel = commentContent["Camera Model:".Length..].Trim();
                }

                continue;
            }

            // Skip empty lines
            if (string.IsNullOrWhiteSpace(line))
                continue;

            // Parse key = value (trim everything after <== which are inline comments)
            var eqIndex = line.IndexOf('=');
            if (eqIndex < 0)
                continue;

            var key = line[..eqIndex].Trim();
            var valuePart = line[(eqIndex + 1)..];

            // Trim inline comment marker <==
            var arrowIndex = valuePart.IndexOf("<==", StringComparison.Ordinal);
            if (arrowIndex >= 0)
                valuePart = valuePart[..arrowIndex];

            // Also trim trailing semicolon comments
            var semiIndex = valuePart.IndexOf(';');
            if (semiIndex >= 0)
                valuePart = valuePart[..semiIndex];

            var value = valuePart.Trim().TrimEnd(';').Trim();

            if (!string.IsNullOrEmpty(key) && !string.IsNullOrEmpty(value))
            {
                // Last write wins — User Settings section overrides Original
                parameters[key] = value;
            }
        }

        return new CamFileInfo(
            FileName: fileName,
            FilePath: Path.GetFullPath(filePath),
            Manufacturer: manufacturer,
            CameraModel: cameraModel,
            Width: GetInt(parameters, "Hactive_Px"),
            Height: GetInt(parameters, "Vactive_Ln"),
            Spectrum: GetString(parameters, "Spectrum", "BW"),
            ColorFormat: GetString(parameters, "ColorFormat", "Y8"),
            TrigMode: GetString(parameters, "TrigMode", "IMMEDIATE"),
            AcquisitionMode: GetString(parameters, "AcquisitionMode", "SNAPSHOT"),
            TapConfiguration: GetString(parameters, "TapConfiguration", "BASE_1T8")
        );
    }

    private static int GetInt(Dictionary<string, string> parameters, string key)
    {
        if (parameters.TryGetValue(key, out var value) && int.TryParse(value, out var result))
            return result;
        return 0;
    }

    private static string GetString(Dictionary<string, string> parameters, string key, string defaultValue)
    {
        return parameters.TryGetValue(key, out var value) ? value : defaultValue;
    }
}
